// layout.js (No "use client" here)
import "./globals.css";
import { Web3Provider } from "@/components/Web3Provider";

export const metadata = {
  title: "Desci",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
